"""login tables

Revision ID: ce4cbffe9af0
Revises: ca06a79aa837
Create Date: 2022-01-14 16:03:44.184903

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce4cbffe9af0"
down_revision = "ca06a79aa837"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=True, server_default="1"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user", sa.Column("hash_id", sa.String(length=36), nullable=False))
    op.add_column(
        "user",
        sa.Column("email_verified", sa.Boolean(), nullable=True, server_default="0"),
    )
    op.add_column(
        "user", sa.Column("token_update", sa.String(length=36), nullable=True)
    )
    op.add_column("user", sa.Column("cell_phone", sa.String(length=32), nullable=True))
    op.add_column("user", sa.Column("genre", sa.String(length=256), nullable=True))
    op.add_column("user", sa.Column("image_key", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("status", sa.Boolean(), nullable=True, server_default="1")
    )
    op.add_column("user", sa.Column("group_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "user", ["hash_id"])
    op.create_foreign_key(None, "user", "group", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "group_id")
    op.drop_column("user", "status")
    op.drop_column("user", "image_key")
    op.drop_column("user", "genre")
    op.drop_column("user", "cell_phone")
    op.drop_column("user", "token_update")
    op.drop_column("user", "email_verified")
    op.drop_column("user", "hash_id")
    op.drop_table("group")
    # ### end Alembic commands ###
